spring.application.name=espe-tech


spring.datasource.url=jdbc:postgresql://localhost:5432/espe_tech_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1

# IMPORTANTE: reemplaza aquí con tu apikey real, no se comparte la apikey real a GitHub
langchain4j.open-ai.chat-model.api-key=TU_API_KEY_AQUI/

langchain4j.open-ai.chat-model.model-name=llama-3.3-70b-versatile
langchain4j.open-ai.chat-model.temperature=0.3
langchain4j.open-ai.chat-model.max-tokens=500

server.port=8080